version: '3.8'
services:
  db:
    image: postgres:15.2-alpine
    container_name: cartaman_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: cartaman
    ports:
      - 5445:5432

