version: '3.8'
services:
  db:
    image: postgres:15.2-alpine
    container_name: cartaman_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: cartaman
    ports:
      - 5445:5432

  app:
    build:
      context: .
    container_name: cartaman-app
    environment:
      ENV: local-docker
      PORT: 9000
      DATABASE_URL: postgres://user:pass@db:5432/cartaman?sslmode=disable
      DATABASE_NAME: cartaman
      DATABASE_MIGRATION_PATH: migrations
    ports:
      - 9000:9000

